baseURL = 'https://helenesauve.github.io/blog/'
languageCode = 'en-us'
title = 'Helene Sauve'
theme = 'cleanwhite'

[params]
    author = "Helene Sauve"
    description = "A blog about my web dev discoveries"
